name: Build

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      # - name: Set up JDK 17
      #   uses: actions/setup-java@v2
      #   with:
      #     java-version: '17'
      #     distribution: 'adopt'
      # - name: Install dotnet 6
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: '6.0.x'
      - name: Run SonarQube Analysis
        uses: highbyte/sonarscan-dotnet@v2.1.5
        with:
          # The key of the SonarQube project
          sonarProjectKey: poc
          # The name of the SonarQube project
          sonarProjectName: sonar poc
          sonarHostname: ${{ secrets.SONAR_HOST_URL }}
          dotnetBuildArguments: ./SonarPOC/SonarPOC.sln
          dotnetTestArguments: ./SonarPOC/SonarPOC.sln --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
          sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

